# I'll add actual docs later
gitRepoUrl = "https://github.com/JovanniJovanni/LuauUtils"
gitSourceBranch = "main"

[[navbar.items]]
href = "https://discord.gg/mhtGUS8"
label = "Discord"
position = "right"

[home]
enabled = true
includeReadme = true

[docusaurus]
url = "https://jovannijovanni.github.io"
baseUrl = "/LuauUtils/"
tagline = "Luau Utils"

[[classOrder]]
section = "DataStructures"
classes = ["Queue", "Stack", "Set"]

[[classOrder]]
section = "Random"
classes = ["WeightedRandom"]

